Draft: Wip/blueprint quickstarts
RedHatInsights/quickstarts pull request #187
Opened 2024-04-25 09:12 UTC by elianerpereira

Adding the quickstart for Blueprints and their customizations, configurations, and image creation.

2024-04-25 11:52 UTC, Hyperkid123 commented
/ok-to-test

2024-04-29 10:09 UTC, elianerpereira commented
I got ACK from all SMEs to merge it. This is now ready to be merged. @Hyperkid123 please, could you help me merge this content?
Thank you.

2024-04-30 06:51 UTC, Hyperkid123 requested changes

2024-04-30 06:51 UTC, Hyperkid123 commented on docs/quickstarts/insights-blueprints/insights-creating-blueprint-images.yml
> +  name: create-blueprint
The name of files and the name of the resources must match. There is a validation error in the pipeline:
```
19:00:11 #13 3.523 Help topic validation error. Error occured in:  docs/quickstarts/insights-blueprints/insights-blueprint.yaml
19:00:11 #13 3.525 panic: open docs/quickstarts/insights-blueprints/insights-blueprint.yaml: no such file or directory

```

2024-04-30 09:00 UTC, ezr-ondrej commented on docs/quickstarts/insights-blueprints/metadata.yml
> +name: insights-blueprint
@elianerpereira this name is the important one I think.
```suggestion
name: insights-creating-blueprint-images
```

2024-04-30 11:16 UTC, ezr-ondrej commented on docs/quickstarts/insights-blueprints/insights-creating-blueprint-images.yml
> +  displayName: Creating a blueprint
```suggestion
  type:
    text: Documentation
    color: orange
  displayName: Creating a blueprint
```

2024-04-30 11:46 UTC, elianerpereira commented
Thank you so much, @ezr-ondrej !!

2024-04-30 12:11 UTC, ezr-ondrej commented
And validation is green @Hyperkid123 :)

2024-04-30 14:58 UTC, ezr-ondrej commented
@elianerpereira can you undraft this PR? :)

2024-04-30 15:03 UTC, elianerpereira commented
> @elianerpereira can you undraft this PR? :)

done, thank you :-)

2024-05-02 07:16 UTC, Hyperkid123 approved these changes

2024-05-02 07:16 UTC, merged